// Array con lista de las principales ciudades del mundo
export const cityOptions = [
    { label: 'Ámsterdam', id: 'amsterdam' },
    { label: 'Atenas', id: 'athens' },
    { label: 'Bangkok', id: 'bangkok' },
    { label: 'Berlín', id: 'berlin' },
    { label: 'Bogotá', id: 'bogota' },
    { label: 'Bruselas', id: 'brussels' },
    { label: 'Budapest', id: 'budapest' },
    { label: 'Buenos Aires', id: 'buenos aires' },
    { label: 'Caracas', id: 'caracas' },
    { label: 'Chicago', id: 'chicago' },
    { label: 'Ciudad de México', id: 'mexico city' },
    { label: 'Copenhague', id: 'copenhagen' },
    { label: 'Dubái', id: 'dubai' },
    { label: 'Dublín', id: 'dublin' },
    { label: 'El Cairo', id: 'cairo' },
    { label: 'Estambul', id: 'istanbul' },
    { label: 'Estocolmo', id: 'stockholm' },
    { label: 'Helsinki', id: 'helsinki' },
    { label: 'Hong Kong', id: 'hong kong' },
    { label: 'Kuala Lumpur', id: 'kuala lumpur' },
    { label: 'Lima', id: 'lima' },
    { label: 'Lisboa', id: 'lisbon' },
    { label: 'Londres', id: 'london' },
    { label: 'Los Ángeles', id: 'los angeles' },
    { label: 'Madrid', id: 'madrid' },
    { label: 'Melbourne', id: 'melbourne' },
    { label: 'Montreal', id: 'montreal' },
    { label: 'Moscú', id: 'moscow' },
    { label: 'Mumbai', id: 'mumbai' },
    { label: 'Nueva York', id: 'new york' },
    { label: 'Oslo', id: 'oslo' },
    { label: 'París', id: 'paris' },
    { label: 'Pekín', id: 'beijing' },
    { label: 'Praga', id: 'prague' },
    { label: 'Reikiavik', id: 'reykjavik' },
    { label: 'Río de Janeiro', id: 'rio de janeiro' },
    { label: 'Roma', id: 'rome' },
    { label: 'Santiago', id: 'santiago' },
    { label: 'São Paulo', id: 'sao paulo' },
    { label: 'Seúl', id: 'seoul' },
    { label: 'Sídney', id: 'sydney' },
    { label: 'Singapur', id: 'singapore' },
    { label: 'Tokio', id: 'tokyo' },
    { label: 'Toronto', id: 'toronto' },
    { label: 'Vancouver', id: 'vancouver' },
    { label: 'Varsovia', id: 'warsaw' },
    { label: 'Viena', id: 'vienna' },
    { label: 'Yakarta', id: 'jakarta' }
  ];
